#! /bin/sh

sxhkd &

bspc config border_width        2    #4
bspc config window_gap          12   #16
bspc config top_padding         30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Chromium desktop=^2
bspc rule -a Chromium -d 2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating
bspc rule -a MPlayer state=floating
bspc rule -a mpv state=floating
bspc rule -a zathura state=floating
bspc config focus_follow_pointer true &

panel &
